# Generated by Django 5.2.13 on 2026-05-01 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('origin', models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('American', 'American'), ('Japan', 'Japan'), ('Korean', 'Korean'), ('England', 'England'), ('France', 'France'), ('Thailand', 'Thailand')], max_length=50, null=True)),
                ('price', models.FloatField()),
                ('import_price', models.FloatField()),
                ('stock', models.BigIntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SELLING', 'SELLING'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('DISCONTINUED', 'DISCONTINUED')], default='NEW', max_length=20)),
                ('view_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Multi-color', 'Multi-color')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logoUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='infrastructure.categorymodel')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'publishers',
                'db_table': 'publishers',
            },
        ),
        migrations.CreateModel(
            name='ElectronicModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.productmodel')),
                ('model', models.CharField(max_length=100, null=True)),
                ('tech_spec', models.JSONField(blank=True, null=True)),
                ('warranty_period', models.DateField(null=True)),
                ('condition', models.CharField(choices=[('new', 'new'), ('open_box', 'open_box'), ('refurbished', 'refurbished')], max_length=50, null=True)),
                ('voltage', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'electronic_product',
                'verbose_name_plural': 'electronic_products',
                'db_table': 'electronic_products',
            },
            bases=('infrastructure.productmodel',),
        ),
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.productmodel')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=20, null=True)),
                ('material', models.CharField(choices=[('cotton', 'cotton'), ('leather', 'leather'), ('polyester', 'polyester')], max_length=100, null=True)),
                ('season', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'fashion_product',
                'verbose_name_plural': 'fashion_products',
                'db_table': 'fashion_products',
            },
            bases=('infrastructure.productmodel',),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.brandmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='infrastructure.categorymodel'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_avatar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infrastructure.productmodel')),
            ],
            options={
                'verbose_name': 'product_image',
                'verbose_name_plural': 'product_images',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.productmodel')),
                ('pub_date', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(choices=[('Vietnamese', 'Vietnamese'), ('English', 'English'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('French', 'French')], max_length=50, null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.authormodel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.publishermodel')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'books',
            },
            bases=('infrastructure.productmodel',),
        ),
    ]
