# Generated by Django 5.2.14 on 2026-05-08 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='format',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='language',
            field=models.CharField(choices=[('Vietnamese', 'Vietnamese'), ('English', 'English'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('French', 'French')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodel',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('open_box', 'open_box'), ('refurbished', 'refurbished')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodel',
            name='model',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodel',
            name='voltage',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='electronicmodel',
            name='warranty_period',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='material',
            field=models.CharField(choices=[('cotton', 'cotton'), ('leather', 'leather'), ('polyester', 'polyester')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='season',
            field=models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Multi-color', 'Multi-color')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='import_price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='origin',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('American', 'American'), ('Japan', 'Japan'), ('Korean', 'Korean'), ('England', 'England'), ('France', 'France'), ('Thailand', 'Thailand')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SELLING', 'SELLING'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('DISCONTINUED', 'DISCONTINUED')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='view_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='StockReservationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('quantity', models.IntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RELEASED', 'RELEASED'), ('CONFIRMED', 'CONFIRMED'), ('EXPIRED', 'EXPIRED')], db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='infrastructure.productmodel')),
            ],
            options={
                'db_table': 'stock_reservations',
                'indexes': [models.Index(fields=['product_id', 'status'], name='stock_reser_product_3ce15a_idx'), models.Index(fields=['order_id'], name='stock_reser_order_i_9784b3_idx'), models.Index(fields=['expires_at'], name='stock_reser_expires_fdd22d_idx')],
            },
        ),
    ]
