# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"1\n\x1aRecommendedProductsRequest\x12\x13\n\x0b\x63\x61tegory_id\x18\x01 \x01(\t\"2\n\x1bRecommendedProductsResponse\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\",\n\x16RelatedProductsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\".\n\x17RelatedProductsResponse\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t2\xf1\x01\n\x15RecommendationService\x12q\n\x16GetRecommendedProducts\x12*.recommendation.RecommendedProductsRequest\x1a+.recommendation.RecommendedProductsResponse\x12\x65\n\x12GetRelatedProducts\x12&.recommendation.RelatedProductsRequest\x1a\'.recommendation.RelatedProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDEDPRODUCTSREQUEST']._serialized_start=40
  _globals['_RECOMMENDEDPRODUCTSREQUEST']._serialized_end=89
  _globals['_RECOMMENDEDPRODUCTSRESPONSE']._serialized_start=91
  _globals['_RECOMMENDEDPRODUCTSRESPONSE']._serialized_end=141
  _globals['_RELATEDPRODUCTSREQUEST']._serialized_start=143
  _globals['_RELATEDPRODUCTSREQUEST']._serialized_end=187
  _globals['_RELATEDPRODUCTSRESPONSE']._serialized_start=189
  _globals['_RELATEDPRODUCTSRESPONSE']._serialized_end=235
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=238
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
