[databases]
# Support both productdb and product-db names for Django connections
productdb = host=product-db port=5432 dbname=product-db user=product-user password=product123456
product-db = host=product-db port=5432 dbname=product-db user=product-user password=product123456

[pgbouncer]
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 25
min_pool_size = 10
reserve_pool_size = 5
reserve_pool_timeout = 3
max_db_connections = 100
max_user_connections = 100

listen_addr = 0.0.0.0
listen_port = 6432

# Trong Docker, nên bỏ logfile để nó hiện lên 'docker logs pgbouncer'
# logfile = /var/log/pgbouncer/pgbouncer.log
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt

admin_users = product-user
stats_users = product-user
