# Generated by Django 4.2.30 on 2026-05-03 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SELLING', 'SELLING'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('DISCONTINUED', 'DISCONTINUED')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
