# Generated by Django 4.2.30 on 2026-05-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_favoriteproduct_name_favoriteproduct_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN'), ('STAFF', 'STAFF')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
