# Generated by Django 4.2.30 on 2026-06-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
