# modules/application/commands/create_stock_reservation_command.py
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import List
from django.db import transaction
from modules.domain.entities.stock_reservation import (
    StockReservation,
    ReservationStatus,
    normalize_reservation_status,
)
from modules.domain.repositories.stock_reservation_repository import StockReservationRepository
from modules.domain.repositories.product_repository import ProductRepository


@dataclass
class CreateStockReservationInput:
    """Input DTO cho create stock reservation command"""
    product_id: str
    order_id: str
    quantity: int
    reservation_duration_minutes: int = 15  # Giữ kho mặc định 15 phút


@dataclass
class CreateStockReservationOutput:
    """Output DTO"""
    reservation_id: str
    product_id: str
    order_id: str
    quantity: int
    expires_at: datetime
    status: str


class CreateStockReservationCommand:
    """Use Case: Tạo stock reservation (giữ kho để chuẩn bị đơn hàng)"""

    def __init__(
        self,
        stock_reservation_repository: StockReservationRepository,
        product_repository: ProductRepository,
    ):
        self.stock_reservation_repository = stock_reservation_repository
        self.product_repository = product_repository

    def execute(self, input_dto: CreateStockReservationInput) -> CreateStockReservationOutput:
        """
        Tạo stock reservation mới và trừ tồn kho ngay lập tức.
        
        Quy trình:
        1. Validate sản phẩm tồn tại
        2. Kiểm tra stock có đủ
        3. Trừ stock của product ngay lập tức
        4. Tạo reservation với trạng thái ACTIVE
        """
        with transaction.atomic():
            # 1. Lấy sản phẩm
            product = self.product_repository.get_by_id(input_dto.product_id)
            if not product:
                raise ValueError(f"Product {input_dto.product_id} not found")

            # 2. Kiểm tra stock có đủ
            available_quantity = int(product.stock or 0)
            if available_quantity < input_dto.quantity:
                raise ValueError(
                    f"Insufficient stock. Available: {available_quantity}, Requested: {input_dto.quantity}"
                )

            # 3. Trừ stock ngay lập tức
            product.stock = available_quantity - input_dto.quantity
            self.product_repository.update(product)

            # 4. Tạo reservation
            expires_at = datetime.utcnow() + timedelta(minutes=input_dto.reservation_duration_minutes)

            reservation = StockReservation(
                id=None,  # Will be generated by repository
                product_id=input_dto.product_id,
                order_id=input_dto.order_id,
                quantity=input_dto.quantity,
                expires_at=expires_at,
                status=ReservationStatus.ACTIVE,
                created_at=datetime.utcnow(),
            )

            # Lưu vào repository
            created_reservation = self.stock_reservation_repository.create(reservation)

            # 5. Return output
            return CreateStockReservationOutput(
                reservation_id=str(created_reservation.id),
                product_id=created_reservation.product_id,
                order_id=created_reservation.order_id,
                quantity=created_reservation.quantity,
                expires_at=created_reservation.expires_at,
                status=normalize_reservation_status(created_reservation.status).value,
            )
