# Generated by Django 5.2.15 on 2026-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sales_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Giá bán'),
        ),
    ]
