type Messages = { [key: string]: string };

const messages: Messages = {
  // common
  "please_login_customer": "Vui lòng đăng nhập tài khoản khách hàng.",
  "cannot_load_profile": "Không thể tải hồ sơ.",
  "cannot_update_profile": "Không thể cập nhật hồ sơ.",
  "select_image": "Chọn ảnh",
  "file_not_image": "Vui lòng chọn file hình ảnh.",
  "image_too_large": "Kích thước ảnh không được vượt quá {max}MB (hiện tại: {actual}MB)",
  "size_limit_caption": "Giới hạn kích thước: {max}MB",
  "saving": "Đang lưu...",
  "save_changes": "Lưu thay đổi",
  "cancel": "Hủy bỏ",
  "back_to_catalog": "Quay lại Danh mục",
  "back_to_products": "Quay lại Sản phẩm",
  "back_to_customers": "Quay lại Danh sách Khách hàng",
  "back_to_staff": "Quay lại Danh sách Nhân viên",
  "loading_products": "Đang tải sản phẩm...",
  "loading_staff_list": "Đang tải danh sách nhân viên...",
  "loading_customer_list": "Đang tải danh sách khách hàng...",
  "loading_profile": "Đang tải hồ sơ...",
  "back_to_cart": "Quay lại Giỏ hàng",
  "back_to_orders": "Quay lại Đơn hàng",
  "back_to_classify": "Quay lại Phân loại",
  "back_to_logistics": "Quay lại Logistics",
  "not_updated": "Chưa cập nhật",
  "cannot_load_addresses": "Không thể tải địa chỉ",
  "cannot_load_methods": "Không thể tải phương thức thanh toán hoặc vận chuyển",
  "cannot_add_address": "Không thể thêm địa chỉ",
  // admin/customer forms
  "cannot_save_customer": "Không thể lưu khách hàng",
  "profile_updated_success": "Cập nhật thông tin thành công!",
  "account_info": "Thông tin tài khoản",
  "avatar_label": "Ảnh đại diện",
  "avatar_file_info": "Tệp: {filename}",
  "last_name_placeholder": "Họ đệm",
  "first_name_placeholder": "Tên",
  "phone_number_label": "Số điện thoại",
  "date_of_birth_label": "Ngày sinh",
  "gender_label": "Giới tính",
  "gender_not_selected": "Chưa chọn",
  "gender_male": "Nam",
  "gender_female": "Nữ",
  "gender_other": "Khác",
  "measurements_section": "Số đo (tuỳ chọn)",
  "height_placeholder": "Chiều cao (cm)",
  "weight_placeholder": "Cân nặng (kg)",
  "foot_length_placeholder": "Bàn chân (cm)",
  
  // Admin Customer List
  "manage_customers": "Quản lý khách hàng",
  "manage_customers_desc": "Theo dõi hồ sơ và trạng thái tài khoản khách hàng trong hệ thống.",
  "create_customer": "Tạo khách hàng mới",
  "search_customers_placeholder": "Tìm theo tên, email, username hoặc số điện thoại...",
  "confirm_delete_customer": "Bạn có chắc chắn muốn xóa khách hàng \"{name}\" không?",
  "active": "Đang hoạt động",
  "inactive": "Ngưng hoạt động",
  "no_customers_found": "Không tìm thấy khách hàng phù hợp.",
  
  // Admin Customer Form
  "edit_customer": "Chỉnh sửa khách hàng",
  "create_new_customer": "Tạo khách hàng mới",
  "username_label": "Tên đăng nhập",
  "last_name_label": "Họ đệm",
  "first_name_label": "Tên",
  "email_label": "Địa chỉ Email",
  "phone_label": "Số điện thoại",
  "height_label": "Chiều cao (cm)",
  "weight_label": "Cân nặng (kg)",
  "foot_length_label": "Độ dài bàn chân (cm)",
  "new_password_label": "Mật khẩu mới",
  "init_password_label": "Mật khẩu khởi tạo",
  "account_status_label": "Trạng thái tài khoản",
  "account_active": "Kích hoạt tài khoản",
  "allow_customer_account": "Cho phép khách hàng đăng nhập và mua hàng",
  "pwd_leave_empty": "Để trống nếu không đổi mật khẩu",
  "pwd_enter_password": "Nhập mật khẩu đăng nhập",
  
  // Admin Staff Form
  "edit_staff": "Chỉnh sửa nhân viên",
  "create_new_staff": "Đăng ký nhân viên mới",
  "work_type_label": "Hình thức làm việc",
  "full_time": "Toàn thời gian",
  "part_time": "Bán thời gian",
  "allow_staff_account": "Cho phép nhân viên đăng nhập và sử dụng hệ thống",
  "update_staff": "Cập nhật thành viên",
  "finish_registration": "Hoàn tất đăng ký",
  // Admin Staff List
  "manage_staff": "Quản lý nhân viên",
  "manage_staff_desc": "Quản lý các thành viên, vai trò và tình trạng làm việc của họ.",
  "create_staff": "Đăng ký nhân viên mới",
  "search_staff_placeholder": "Tìm theo tên hoặc mã nhân viên...",
  "confirm_delete_staff": "Bạn có chắc chắn muốn xóa nhân viên \"{name}\" không?",
  "no_staff_found": "Không tìm thấy thành viên nào phù hợp.",
  "filter_all": "Tất cả",
  
  // Admin Product List
  "manage_inventory": "Quản lý kho hàng",
  "manage_inventory_desc": "Chỉnh sửa và theo dõi mức tồn kho trên tất cả danh mục.",
  "search_products_placeholder": "Tìm kiếm sản phẩm...",
  "product_actions": "Thao tác",
  "product_name": "Tên sản phẩm",
  "category": "Danh mục",
  "origin": "Xuất xứ",
  "quantity": "Số lượng",
  "price": "Giá",
  "no_products_found": "Không tìm thấy sản phẩm nào.",
  // Admin Product Form
  "edit_product": "Chỉnh sửa sản phẩm",
  "create_new_product": "Thêm sản phẩm mới",
  "product_name_label": "Tên sản phẩm",
  "product_name_placeholder": "Nhập tên sản phẩm...",
  "category_label": "Danh mục",
  "sub_category_label": "Danh mục phụ",
  "sub_category_placeholder": "VD: Tiểu thuyết, Laptop...",
  "product_description_label": "Mô tả sản phẩm",
  "product_description_placeholder": "Mô tả các đặc tính của sản phẩm...",
  "origin_label": "Xuất xứ",
  "origin_placeholder": "Việt Nam, Mỹ...",
  "stock_quantity_label": "Số lượng tồn kho",
  "product_image_label": "Hình ảnh sản phẩm",
  "image_url_placeholder": "Đường dẫn hình ảnh...",
  "price_label_vnd": "Giá bán (VNĐ)",
  "vnd_symbol": "đ",
  "category_books": "Sách",
  "category_electronics": "Điện tử",
  "category_fashion": "Thời trang",
  
  // Cart
  "my_cart": "Giỏ hàng của tôi",
  "empty_cart": "Giỏ hàng đang trống",
  "empty_cart_desc": "Hãy xem danh mục của chúng tôi để tìm kiếm những sản phẩm chất lượng nhất.",
  "select_all": "Chọn tất cả",
  "total_items": "{count} sản phẩm được chọn",
  // Auth / Login / Register
  "app_title": "BECShop Commerce",
  "login_title_customer": "Đăng nhập khách hàng",
  "login_title_admin": "Đăng nhập admin",
  "login_title_staff": "Đăng nhập staff",
  "username_placeholder": "Tên đăng nhập",
  "password_placeholder": "••••••••",
  "password_label": "Mật khẩu",
  "logging_in": "Đang đăng nhập...",
  "login_button": "Đăng nhập",
  "login_failed": "Đăng nhập thất bại",
  "no_account_prompt": "Chưa có tài khoản?",
  "create_account": "Tạo tài khoản",
  "staff_login": "Nhân viên đăng nhập",
  "admin_login": "Quản trị viên đăng nhập",
  "need_access_contact_admin": "Cần quyền truy cập? Liên hệ quản trị hệ thống.",

  "register_title": "Đăng ký tài khoản",
  "registering": "Đang đăng ký...",
  "create_account_button": "Tạo tài khoản",
  "please_fill_required": "Vui lòng nhập đầy đủ các trường bắt buộc.",
  "passwords_do_not_match": "Mật khẩu xác nhận không khớp.",
  "registration_failed": "Đăng ký thất bại. Vui lòng thử lại sau.",
  "registration_error_400": "Thông tin đăng ký chưa hợp lệ. Vui lòng kiểm tra lại các trường bị báo lỗi.",
  "registration_error_401": "Phiên đăng ký không hợp lệ. Vui lòng tải lại trang và thử lại.",
  "registration_error_403": "Bạn không có quyền thực hiện thao tác này.",
  "registration_error_409": "Tên đăng nhập hoặc email đã tồn tại. Vui lòng chọn thông tin khác.",
  "registration_error_500": "Hệ thống đang gặp sự cố khi đăng ký. Vui lòng thử lại sau.",
  // Product Detail / Category list
  "in_stock": "{count} Còn hàng",
  "out_of_stock": "Hết hàng",
  "free_shipping": "Miễn phí vận chuyển",
  "genuine_product": "Sản phẩm chính hãng",
  "add_to_cart": "Thêm giỏ hàng",
  "buy_now": "Mua ngay",
  "add": "Thêm",
  "best_seller": "Bán chạy",
  "manufacturer": "Cơ sở sản xuất",
  "imported_prefix": "Nhập khẩu: {value}",
  "stock_label": "Tồn kho",
  "quality_label": "Chất lượng",
  "quality_certified": "Chứng nhận 100%",
  "vnd_text": "VNĐ",

  "filter_title": "Bộ lọc",
  "clear_filters": "Xóa lọc",
  "range_from": "Từ",
  "range_to": "Đến",
  "all_label": "Tất cả",
  "enter_field": "Nhập {field}",
  "stars_or_more": "{count} sao trở lên",
  "category_not_found": "Không tìm thấy danh mục này.",
  // Contact View
  "contact_title_badge": "Liên hệ BECShop",
  "contact_title": "Chúng tôi luôn sẵn sàng hỗ trợ bạn",
  "contact_description": "Gửi câu hỏi về đơn hàng, thanh toán hoặc tư vấn sản phẩm. Đội ngũ CSKH sẽ phản hồi trong thời gian sớm nhất.",
  "contact_hotline": "Hotline",
  "contact_hotline_hours": "Hỗ trợ 8:00 - 22:00 mỗi ngày",
  "contact_email": "Email",
  "contact_email_response": "Phản hồi trong vòng 24 giờ",
  "contact_office": "Văn phòng",
  "contact_office_info": "Tiếp nhận đối tác và doanh nghiệp",
  "contact_form_title": "Gửi yêu cầu hỗ trợ",
  "contact_form_name": "Họ và tên",
  "contact_form_email": "Email",
  "contact_form_phone": "Số điện thoại",
  "contact_form_subject": "Chủ đề",
  "contact_form_message": "Nội dung cần hỗ trợ...",
  "contact_form_processing_time": "Thời gian xử lý trung bình: 2 - 6 giờ làm việc",
  "contact_form_submit": "Gửi yêu cầu",
  // Order History View
  "order_history_title": "Lịch sử mua hàng",
  "order_history_description": "Theo dõi kiện hàng và xem lại lịch sử giao dịch.",
  "order_history_empty": "Không tìm thấy đơn hàng",
  "order_history_empty_desc": "Hãy bắt đầu khám phá các bộ sưu tập của chúng tôi!",
  "order_history_to_shop": "Đến Cửa hàng",
  "order_history_number": "Đơn hàng #{id}",
  "order_history_separator": "• {count} sản phẩm",
  "order_status_awaiting_confirmation": "Chờ xác nhận",
  "order_status_awaiting_pickup": "Chờ lấy hàng",
  "order_status_awaiting_delivery": "Đang giao hàng",
  "order_status_delivered": "Đã giao hàng",
  "order_status_canceled": "Đã hủy",
  // Checkout View
  "checkout_title": "Thanh toán giao dịch",
  "checkout_address_label": "Địa điểm giao hàng",
  "checkout_add_new_address": "Thêm địa chỉ mới...",
  "checkout_add_button": "Thêm",
  "checkout_loading_addresses": "Đang tải địa chỉ...",
  "checkout_input_address": "Nhập địa chỉ giao hàng đầy đủ...",
  "checkout_delete_address": "Xóa địa chỉ đang chọn",
  "checkout_delete_address_error": "Không thể xóa địa chỉ",
  "checkout_confirm_delete_address": "Xóa địa chỉ này?",
    // Customer Addresses View
    "addresses_title": "Địa chỉ giao hàng",
    "addresses_description": "Quản lý danh sách địa chỉ để thanh toán nhanh hơn.",
    "addresses_add_section": "Thêm địa chỉ mới",
    "addresses_placeholder": "VD: 12 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    "addresses_add_button": "Thêm",
    "addresses_saving": "Đang lưu...",
    "addresses_loading": "Đang tải địa chỉ...",
    "addresses_empty": "Chưa có địa chỉ nào.",
    "addresses_cannot_load": "Không thể tải địa chỉ",
    "addresses_cannot_add": "Không thể thêm địa chỉ",
    "addresses_cannot_delete": "Không thể xóa địa chỉ",
    "addresses_confirm_delete": "Xóa địa chỉ này?",
    // Order Details View
    "order_details_title": "Chi tiết đơn hàng",
    "order_details_status_label": "Trạng thái:",
    "order_details_status_processing": "Đang xử lý",
    "order_details_status_delivered": "Đã giao",
    "order_details_payment_label": "Thanh toán",
    "order_details_payment_paid": "Đã trả",
    "order_details_payment_unpaid": "Chưa trả",
    "order_details_items_title": "Sản phẩm trong đơn",
    "order_details_quantity_label": "SL:",
    "order_details_review_button": "Viết nhận xét",
    "order_details_shipping_address": "Địa chỉ giao hàng",
    "order_details_shipping_method": "Phương thức vận chuyển",
    "order_details_shipping_standard": "Giao hàng tiêu chuẩn",
    "order_details_shipping_express": "Giao hàng hỏa tốc",
    "order_details_payment_method": "Phương thức thanh toán",
    "order_details_total_items": "Tổng cộng tiền hàng",
    "order_details_shipping_fee": "Phí vận chuyển",
    "order_details_total_payment": "Tổng thanh toán",
    // Review View
    "review_title": "Chia sẻ trải nghiệm",
    "review_description": "Phản hồi của bạn giúp người khác đưa ra lựa chọn tốt hơn.",
    "review_quality_label": "Chất lượng sản phẩm như thế nào?",
    "review_form_label": "Viết đánh giá của bạn",
    "review_placeholder": "Cho chúng tôi biết bạn thích hoặc chưa hài lòng về điều gì...",
    "review_submit_button": "Gửi đánh giá",
  "checkout_shipping_label": "Phương thức vận chuyển",
  "checkout_payment_label": "Phương thức thanh toán",
  "checkout_summary_label": "Tóm tắt đơn hàng",
  "checkout_item_quantity": "SỐ LƯỢNG: {count}",
  "checkout_subtotal": "Tổng tiền hàng",
  "checkout_shipping_fee": "Phí vận chuyển",
  "checkout_total": "Tổng cộng",
  "checkout_order_button": "Hoàn tất thanh toán",
  "checkout_ssl_info": "Mã hóa AES-256 TLS đang hoạt động",
};

export const priorityKeys = new Set<string>([
  "please_login_customer",
  "cannot_load_profile",
  "cannot_update_profile",
  "file_not_image",
  "image_too_large",
  "saving",
  "save_changes",
  "cancel",
  "back_to_catalog",
  "back_to_products",
  "back_to_customers",
  "back_to_staff",
  "loading_products",
  "loading_staff_list",
  "loading_customer_list",
  "loading_profile",
  "back_to_cart",
  "back_to_orders",
  "back_to_classify",
  "back_to_logistics",
  "cannot_load_addresses",
  "cannot_load_methods",
  "cannot_add_address",
  "cannot_save_customer",
  "manage_customers",
  "create_customer",
  "search_customers_placeholder",
  "confirm_delete_customer",
  "no_customers_found",
  "edit_customer",
  "create_new_customer",
  "username_label",
  "email_label",
  "account_status_label",
  "edit_staff",
  "create_new_staff",
  "manage_inventory",
  "search_products_placeholder",
  "no_products_found",
  "my_cart",
  "empty_cart",
  "empty_cart_desc",
]);

export function isPriorityKey(key: string) {
  return priorityKeys.has(key);
}

export function t(key: string, params?: Record<string, string | number>) {
  let msg = messages[key] || key;
  if (params) {
    for (const k of Object.keys(params)) {
      msg = msg.replace(new RegExp(`\\{${k}\\}`, "g"), String(params[k]));
    }
  }
  return msg;
}
